Parameters:
  CodeCommitRepoName:
    Type: String
  LambdaFunctionTrigger:
    Type: String

Resources:
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref CodeCommitRepoName
      Triggers:
        - DestinationArn: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${LambdaFunctionTrigger}
          Events: 
            - all 
          Name: !Sub ${CodeCommitRepoName}
          Branches:
            - all

#Outputs:
#  CodeCommitRepoOutput:
#    Value: !Ref CodeCommitRepo
#    Export:
#      Name: CodeCommitRepoExport
