Parameters:
  BucketNameCF:
    Type: String
  BucketName:
    Type: String

Resources:
  CodeCommitCodeBuildLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketNameCF}.s3.${AWS::Region}.amazonaws.com/create_codecommit_repo.yml
      Parameters:
        CodeCommitRepoName: "codecommit_codebuild_lambda_trigger"
        LambdaFunctionTrigger: !ImportValue LambdaCodeCommitTrigger
  LambdaS3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketNameCF}.s3.${AWS::Region}.amazonaws.com/create_s3_bucket.yml
      Parameters:
        BucketName: !Ref BucketName