Parameters:
  AppRepo:
    Description: "App Repo Name"
    Type: String
  EmailEndpoint:
    Description: "This is the email address for the SNS notifications"
    Type: String

Resources:
  CodeCommitNotification:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties: 
      DetailType: FULL
      EventTypeIds: 
        - codecommit-repository-comments-on-commits
        - codecommit-repository-comments-on-pull-requests
        - codecommit-repository-approvals-status-changed
        - codecommit-repository-approvals-rule-override
        - codecommit-repository-pull-request-created
        - codecommit-repository-pull-request-source-updated
        - codecommit-repository-pull-request-status-changed
        - codecommit-repository-pull-request-merged
        - codecommit-repository-branches-and-tags-created
        - codecommit-repository-branches-and-tags-deleted
        - codecommit-repository-branches-and-tags-updated
      Name: CodeCommitNotificationSNSRule
      Resource: !Sub "arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${AppRepo}"
      Status: ENABLED
      Targets: 
        - TargetType: SNS
          TargetAddress: !Ref CodeCommitNotificationSNSTopic
  CodeCommitNotificationSNSTopic:  
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: CodeCommitNotificationSNSTopic
  CodeCommitNotificationSNSTopicAccessPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument: 
        {
          "Version": "2008-10-17",
          "Id": "__default_policy_ID",
          "Statement": [
            {
              "Sid": "__default_statement_ID",
              "Effect": "Allow",
              "Principal": {
                "AWS": "*"
              },
              "Action": [
                "SNS:GetTopicAttributes",
                "SNS:SetTopicAttributes",
                "SNS:AddPermission",
                "SNS:RemovePermission",
                "SNS:DeleteTopic",
                "SNS:Subscribe",
                "SNS:ListSubscriptionsByTopic",
                "SNS:Publish",
                "SNS:Receive"
              ],
              "Resource": !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${CodeCommitNotificationSNSTopic}",
              "Condition": {
                "StringEquals": {
                  "AWS:SourceOwner": "${AWS::AccountId}"
                }
              }
            },
            {
              "Sid": "AWSCodeStarNotifications_publish",
              "Effect": "Allow",
              "Principal": {
                "Service": "codestar-notifications.amazonaws.com"
              },
              "Action": "SNS:Publish",
              "Resource": "arn:aws:sns:*:*:*"
            }
          ]
        }
      Topics: 
        - !Ref CodeCommitNotificationSNSTopic
  CodeCommitNotificationSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref EmailEndpoint
      Protocol: email
      TopicArn: !Ref CodeCommitNotificationSNSTopic
